export const AI_TECHNIQUES = [
  { id: 1, paradigm: "Logistic Regression", layer: "Transaction Processing", formula: "min_w −(1/N)Σ[yᵢlog(ŷᵢ) + (1−yᵢ)log(1−ŷᵢ)]", goal: "Classification Accuracy", gain: 12, complexity: "O(T·N·d)", maturity: "Mature", category: "Supervised", color: "#3B82F6", description: "Minimizes empirical risk for binary classification in financial and transaction systems. Foundation of interpretable AI in enterprise." },
  { id: 2, paradigm: "SVM", layer: "Risk Assessment", formula: "min_w (1/2)|w|² + C·Σmax(0, 1−yᵢ(wᵀxᵢ+b))", goal: "Margin Maximization", gain: 15, complexity: "O(N³)", maturity: "Mature", category: "Supervised", color: "#6366F1", description: "Maximizes decision margin for robust risk classification. Excels in high-dimensional enterprise feature spaces." },
  { id: 3, paradigm: "Random Forest", layer: "CRM Analytics", formula: "IG(D,A) = H(D) − Σ(|Dᵥ|/|D|)·H(Dᵥ)", goal: "Variance Reduction", gain: 18, complexity: "O(M·N·log(N)·d)", maturity: "Mature", category: "Ensemble", color: "#8B5CF6", description: "Ensemble of decision trees reducing variance through information gain splitting. Handles nonlinear CRM patterns effectively." },
  { id: 4, paradigm: "Deep Neural Network", layer: "Enterprise Forecasting", formula: "h = σ(Wx + b)", goal: "Nonlinear Pattern Learning", gain: 22, complexity: "O(T·N·|W|)", maturity: "Advanced", category: "Deep Learning", color: "#A855F7", description: "Hierarchical feature learning through nonlinear transformations. Powers demand forecasting and enterprise analytics." },
  { id: 5, paradigm: "CNN", layer: "Image-based IS", formula: "f(x) = Softmax(W₂σ(W₁x))", goal: "Feature Abstraction", gain: 25, complexity: "O(T·N·ΣKₗ²·Cₗ₋₁·Cₗ·Hₗ·Wₗ)", maturity: "Advanced", category: "Deep Learning", color: "#C026D3", description: "Convolutional feature extraction for visual information systems — quality inspection, document intelligence, medical imaging." },
  { id: 6, paradigm: "Transformer", layer: "Knowledge Systems", formula: "Attention(Q,K,V) = softmax(QKᵀ/√dₖ)V", goal: "Context Modeling", gain: 28, complexity: "O(T·N·(L²seq·d + Lseq·d²))", maturity: "Emerging", category: "Deep Learning", color: "#7C3AED", description: "Self-attention mechanism enabling contextual reasoning in enterprise knowledge systems and document intelligence." },
  { id: 7, paradigm: "Reinforcement Learning", layer: "Decision Support", formula: "Vᵖ(s) = Eᵖ[Σγᵗ·Rₜ₊₁ | S₀=s]", goal: "Long-Term Reward", gain: 20, complexity: "O(|S|·|A|)", maturity: "Emerging", category: "Adaptive", color: "#2563EB", description: "Sequential decision optimization for dynamic pricing, resource allocation, and adaptive workflow management." },
  { id: 8, paradigm: "Autoencoder", layer: "Cybersecurity", formula: "min_θ,φ (1/N)Σ|xᵢ − gφ(fθ(xᵢ))|²", goal: "Anomaly Detection", gain: 23, complexity: "O(T·N·|W|)", maturity: "Advanced", category: "Deep Learning", color: "#1D4ED8", description: "Unsupervised representation learning for cybersecurity anomaly detection in network traffic and financial systems." },
  { id: 9, paradigm: "Graph Neural Network", layer: "Network Monitoring", formula: "hᵥ⁽ᵏ⁾ = σ(W⁽ᵏ⁾·AGG({hᵤ⁽ᵏ⁻¹⁾ ∀u∈N(v)}))", goal: "Relational Learning", gain: 27, complexity: "O(T·L·(|V|+|E|)·d²)", maturity: "Advanced", category: "Graph", color: "#0891B2", description: "Graph-based reasoning for enterprise network monitoring and relational knowledge representation in semantic IS." },
  { id: 10, paradigm: "Knowledge-Based Reasoning", layer: "Semantic IS", formula: "KB ⊨ q, where G = (V, E)", goal: "Logical Consistency", gain: 16, complexity: "O(2ᵛ)", maturity: "Mature", category: "Symbolic", color: "#059669", description: "Logical inference over knowledge graphs enabling domain-aware semantic reasoning in enterprise systems." },
  { id: 11, paradigm: "Federated Learning", layer: "Distributed IS", formula: "w_global = Σ(nₖ/N)·wₖ_local", goal: "Privacy Preservation", gain: 19, complexity: "O(R·K·C_local)", maturity: "Emerging", category: "Distributed", color: "#10B981", description: "Privacy-preserving collaborative learning across distributed enterprise nodes without centralizing sensitive data." },
  { id: 12, paradigm: "Hybrid ML + KB", layer: "Smart Enterprise", formula: "ŷ = α·f_ML(x) + (1−α)·f_KB(x)", goal: "Robust Decision Fusion", gain: 30, complexity: "O(C_ML + C_KB)", maturity: "Emerging", category: "Hybrid", color: "#F59E0B", description: "Fusion of statistical learning and symbolic reasoning — highest performance gain of all paradigms in enterprise settings." },
  { id: 13, paradigm: "Ensemble Learning", layer: "Enterprise DSS", formula: "ŷ = Σαₘ·hₘ(x)", goal: "Bias-Variance Tradeoff", gain: 26, complexity: "O(M·C_base)", maturity: "Mature", category: "Ensemble", color: "#EF4444", description: "Weighted combination of base classifiers for robust decision support system outputs with reduced overfitting." },
  { id: 14, paradigm: "Edge AI", layer: "Real-Time Systems", formula: "min_θ L(θ) s.t. Memory<M, Latency<T", goal: "Latency Minimization", gain: 35, complexity: "O(|W_pruned|)", maturity: "Emerging", category: "Distributed", color: "#F97316", description: "Latency reduction of 35% through constrained optimization for real-time distributed enterprise systems." },
  { id: 15, paradigm: "Explainable AI (XAI)", layer: "Governance Layer", formula: "φᵢ = Σ (|S|!(|F|−|S|−1)!/|F|!)·[f(S∪{i})−f(S)]", goal: "Interpretability", gain: 40, complexity: "O(2ᵈ)", maturity: "Advanced", category: "Governance", color: "#EC4899", description: "Shapley value attribution for model transparency — 40% interpretability gain enabling regulatory compliance in critical IS." },
];

export const ARCHITECTURE_MODULES = [
  { id: "data", name: "Data Acquisition", icon: "database", position: 1, description: "Multi-source data ingestion from enterprise systems, IoT, APIs, and transactional databases. Handles structured and unstructured data streams with real-time and batch processing capabilities.", components: ["Stream Ingestion", "Batch ETL", "Data Quality Checks", "Schema Normalization", "Source Connectors"], color: "#3B82F6" },
  { id: "processing", name: "Intelligent Processing", icon: "cpu", position: 2, description: "AI-powered data transformation applying ML models, feature engineering, NLP, and computer vision to extract high-level abstractions from raw enterprise data.", components: ["Feature Engineering", "NLP Pipeline", "Computer Vision", "Model Inference", "Knowledge Extraction"], color: "#8B5CF6" },
  { id: "decision", name: "Decision Intelligence", icon: "brain", position: 3, description: "Hybrid reasoning engine combining predictive ML models with symbolic knowledge-based reasoning for explainable, trustworthy enterprise decision support.", components: ["Predictive Models", "Knowledge Graph", "Hybrid Fusion", "XAI Engine", "Policy Optimizer"], color: "#A855F7" },
  { id: "feedback", name: "Feedback Optimization", icon: "refresh-cw", position: 4, description: "Closed-loop adaptive system using reinforcement learning and performance metrics to continuously optimize model weights, decision policies, and system behavior.", components: ["RL Policy Updates", "Performance Monitoring", "A/B Testing", "Model Retraining", "Drift Detection"], color: "#EC4899" },
];

export const RESEARCH_DIRECTIONS = [
  { id: 1, title: "Neuro-Symbolic Hybrid Models", description: "Deep learning combined with knowledge graphs for superior reasoning abilities — bridging the gap between statistical pattern recognition and logical inference.", refs: "[11]", horizon: "2025-2027", progress: 35, icon: "🧠" },
  { id: 2, title: "Scalable Transformer Variants", description: "Efficient attention mechanisms reducing quadratic complexity O(L²seq·d) for large-scale enterprise text and transactional dataset processing.", refs: "[6]", horizon: "2024-2026", progress: 55, icon: "⚡" },
  { id: 3, title: "Intrinsically Transparent AI", description: "Moving from post-hoc XAI (Shapley explanations) to architectures with interpretability built into design — trustworthy AI for healthcare and finance IS.", refs: "[12,13]", horizon: "2025-2028", progress: 25, icon: "🔍" },
  { id: 4, title: "Privacy-Preserving Distributed IS", description: "Federated learning with adversarial robustness and reduced communication overhead for distributed enterprise data collaboration without centralization.", refs: "[14,15]", horizon: "2024-2026", progress: 60, icon: "🔐" },
  { id: 5, title: "Autonomous Self-Optimizing Systems", description: "RL combined with real-time analytics for enterprise systems that continuously adapt decision strategies — autonomous, converging, and explainable.", refs: "[7,9]", horizon: "2026-2029", progress: 20, icon: "🤖" },
];

export const PERFORMANCE_METRICS = [
  { name: "Logistic Regression", accuracy: 82, precision: 80, recall: 79, f1: 80, auc: 84, efficiency: 95, gain: 12 },
  { name: "SVM", accuracy: 85, precision: 84, recall: 82, f1: 83, auc: 86, efficiency: 40, gain: 15 },
  { name: "Random Forest", accuracy: 88, precision: 87, recall: 86, f1: 86, auc: 89, efficiency: 70, gain: 18 },
  { name: "Deep Neural Network", accuracy: 91, precision: 90, recall: 89, f1: 90, auc: 92, efficiency: 60, gain: 22 },
  { name: "CNN", accuracy: 93, precision: 92, recall: 91, f1: 92, auc: 94, efficiency: 55, gain: 25 },
  { name: "Transformer", accuracy: 95, precision: 94, recall: 93, f1: 94, auc: 96, efficiency: 30, gain: 28 },
  { name: "Reinforcement Learning", accuracy: 87, precision: 85, recall: 88, f1: 86, auc: 88, efficiency: 65, gain: 20 },
  { name: "Autoencoder", accuracy: 89, precision: 88, recall: 90, f1: 89, auc: 91, efficiency: 62, gain: 23 },
  { name: "GNN", accuracy: 92, precision: 91, recall: 90, f1: 91, auc: 93, efficiency: 45, gain: 27 },
  { name: "Knowledge-Based", accuracy: 84, precision: 86, recall: 81, f1: 83, auc: 85, efficiency: 80, gain: 16 },
  { name: "Federated Learning", accuracy: 86, precision: 85, recall: 84, f1: 85, auc: 87, efficiency: 50, gain: 19 },
  { name: "Hybrid ML+KB", accuracy: 96, precision: 95, recall: 94, f1: 95, auc: 97, efficiency: 52, gain: 30 },
  { name: "Ensemble", accuracy: 93, precision: 92, recall: 91, f1: 92, auc: 94, efficiency: 48, gain: 26 },
  { name: "Edge AI", accuracy: 85, precision: 83, recall: 84, f1: 83, auc: 86, efficiency: 90, gain: 35 },
  { name: "XAI", accuracy: 88, precision: 87, recall: 86, f1: 87, auc: 89, efficiency: 35, gain: 40 },
];
